version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing app dependencies...
      - yarn install
      - npm install -g serverless
      - yarn add @sls-next/serverless-component@3.6.0

  build:
    commands:
      - export NODE_OPTIONS=--max_old_space_size=8192
      - cp serverless-production.yml serverless.yml
#      - aws s3 sync s3://magpie-serverless-state-bucket/alfm-frontend/production/.serverless .serverless --delete
      - npx serverless
      - aws s3 sync .serverless s3://magpie-serverless-state-bucket/alfm-frontend/production/.serverless --delete
